/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.19.1
// source: Proto/monitor_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var Proto_common_pb = require('../Proto/common_pb.js')
const proto = require('./monitor_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.MonitorClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.MonitorPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.MonitorLocationRequest,
 *   !proto.MonitorLocationEvent>}
 */
const methodDescriptor_Monitor_MonitorLocation = new grpc.web.MethodDescriptor(
  '/Monitor/MonitorLocation',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.MonitorLocationRequest,
  proto.MonitorLocationEvent,
  /**
   * @param {!proto.MonitorLocationRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.MonitorLocationEvent.deserializeBinary
);


/**
 * @param {!proto.MonitorLocationRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.MonitorLocationEvent>}
 *     The XHR Node Readable Stream
 */
proto.MonitorClient.prototype.monitorLocation =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/Monitor/MonitorLocation',
      request,
      metadata || {},
      methodDescriptor_Monitor_MonitorLocation);
};


/**
 * @param {!proto.MonitorLocationRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.MonitorLocationEvent>}
 *     The XHR Node Readable Stream
 */
proto.MonitorPromiseClient.prototype.monitorLocation =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/Monitor/MonitorLocation',
      request,
      metadata || {},
      methodDescriptor_Monitor_MonitorLocation);
};


module.exports = proto;

