/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.19.1
// source: Proto/user_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./user_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.UserClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.UserPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.RegisterRequest,
 *   !proto.RegisterResponse>}
 */
const methodDescriptor_User_Register = new grpc.web.MethodDescriptor(
  '/User/Register',
  grpc.web.MethodType.UNARY,
  proto.RegisterRequest,
  proto.RegisterResponse,
  /**
   * @param {!proto.RegisterRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.RegisterResponse.deserializeBinary
);


/**
 * @param {!proto.RegisterRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.RegisterResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.RegisterResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.UserClient.prototype.register =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/User/Register',
      request,
      metadata || {},
      methodDescriptor_User_Register,
      callback);
};


/**
 * @param {!proto.RegisterRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.RegisterResponse>}
 *     Promise that resolves to the response
 */
proto.UserPromiseClient.prototype.register =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/User/Register',
      request,
      metadata || {},
      methodDescriptor_User_Register);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.LoginRequest,
 *   !proto.LoginResponse>}
 */
const methodDescriptor_User_Login = new grpc.web.MethodDescriptor(
  '/User/Login',
  grpc.web.MethodType.UNARY,
  proto.LoginRequest,
  proto.LoginResponse,
  /**
   * @param {!proto.LoginRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.LoginResponse.deserializeBinary
);


/**
 * @param {!proto.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.LoginResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.LoginResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.UserClient.prototype.login =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/User/Login',
      request,
      metadata || {},
      methodDescriptor_User_Login,
      callback);
};


/**
 * @param {!proto.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.LoginResponse>}
 *     Promise that resolves to the response
 */
proto.UserPromiseClient.prototype.login =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/User/Login',
      request,
      metadata || {},
      methodDescriptor_User_Login);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.CheckBalanceRequest,
 *   !proto.CheckBalanceResponse>}
 */
const methodDescriptor_User_CheckBalance = new grpc.web.MethodDescriptor(
  '/User/CheckBalance',
  grpc.web.MethodType.UNARY,
  proto.CheckBalanceRequest,
  proto.CheckBalanceResponse,
  /**
   * @param {!proto.CheckBalanceRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.CheckBalanceResponse.deserializeBinary
);


/**
 * @param {!proto.CheckBalanceRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.CheckBalanceResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.CheckBalanceResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.UserClient.prototype.checkBalance =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/User/CheckBalance',
      request,
      metadata || {},
      methodDescriptor_User_CheckBalance,
      callback);
};


/**
 * @param {!proto.CheckBalanceRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.CheckBalanceResponse>}
 *     Promise that resolves to the response
 */
proto.UserPromiseClient.prototype.checkBalance =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/User/CheckBalance',
      request,
      metadata || {},
      methodDescriptor_User_CheckBalance);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.AddFundsRequest,
 *   !proto.AddFundsResponse>}
 */
const methodDescriptor_User_AddFunds = new grpc.web.MethodDescriptor(
  '/User/AddFunds',
  grpc.web.MethodType.UNARY,
  proto.AddFundsRequest,
  proto.AddFundsResponse,
  /**
   * @param {!proto.AddFundsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.AddFundsResponse.deserializeBinary
);


/**
 * @param {!proto.AddFundsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.AddFundsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.AddFundsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.UserClient.prototype.addFunds =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/User/AddFunds',
      request,
      metadata || {},
      methodDescriptor_User_AddFunds,
      callback);
};


/**
 * @param {!proto.AddFundsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.AddFundsResponse>}
 *     Promise that resolves to the response
 */
proto.UserPromiseClient.prototype.addFunds =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/User/AddFunds',
      request,
      metadata || {},
      methodDescriptor_User_AddFunds);
};


module.exports = proto;

