/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.19.1
// source: Proto/vehicle_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var Proto_common_pb = require('../Proto/common_pb.js')
const proto = require('./vehicle_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.VehicleClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.VehiclePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.UpdatePositionRequest,
 *   !proto.UpdatePositionResponse>}
 */
const methodDescriptor_Vehicle_UpdatePosition = new grpc.web.MethodDescriptor(
  '/Vehicle/UpdatePosition',
  grpc.web.MethodType.UNARY,
  proto.UpdatePositionRequest,
  proto.UpdatePositionResponse,
  /**
   * @param {!proto.UpdatePositionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.UpdatePositionResponse.deserializeBinary
);


/**
 * @param {!proto.UpdatePositionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.UpdatePositionResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.UpdatePositionResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.VehicleClient.prototype.updatePosition =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Vehicle/UpdatePosition',
      request,
      metadata || {},
      methodDescriptor_Vehicle_UpdatePosition,
      callback);
};


/**
 * @param {!proto.UpdatePositionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.UpdatePositionResponse>}
 *     Promise that resolves to the response
 */
proto.VehiclePromiseClient.prototype.updatePosition =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Vehicle/UpdatePosition',
      request,
      metadata || {},
      methodDescriptor_Vehicle_UpdatePosition);
};


module.exports = proto;

